### ISSUE TITLE
书没了是什么意思

### ISSUE THREAD

**Issue by ivysrono** [guoruibiao/Effective-Python#1]
看到错别字正想来提交PR

**Comment by guoruibiao** [comment]
感谢您的issue。书的事是一个意外。
桑心:cry:

**Comment by ivysrono** [comment]
一眼看去错别字不少，标点和空格的使用也很不规范，本阿里想边看边改的，结果发现了这么悲伤的故事……

**Comment by ivysrono** [comment]
一眼看去错别字不少，标点和空格的使用也很不规范，本来想边看边改的，结果发现了这么悲伤的故事……

**Comment by zhanglongqi** [comment]
因为被出版社抢先翻译完出版了吗？
