### ISSUE TITLE
了解字节，字符串以及unicode# 了解字节，字符串以及unicode之间的区别的错误

### ISSUE THREAD

**Issue by lin344902118** [guoruibiao/Effective-Python#3]
这个地方有个错误
在Python3中
你将需要一个方法，接收str或者bytes，总是来返回str类型的数据。如下：
def to_str(bytes_or_str):
    if isinstance(bytes_or_str,bytes):
        value = bytes_or_str.encode('utf-8')
    else:
        value = bytes_or_str
    # str类型的数据
    return value
encode应该改成decode才对吧，python3里面bytes是没有encode函数的
python2也是

**Comment by guoruibiao** [comment]
笔误，你说得对:up:
